version: '3.8'
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smartcity
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d smartcity"]
      interval: 5s
      timeout: 5s
      retries: 5

  resident-api:
    build:
      context: .
      dockerfile: ./services/resident/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/smartcity?schema=public"
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  report-api:
    build:
      context: .
      dockerfile: ./services/report/Dockerfile
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/smartcity?schema=public"
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  alert-api:
    build:
      context: .
      dockerfile: ./services/alert/Dockerfile
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/smartcity?schema=public"
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki

volumes:
  postgres_data: